# Funding options displayed on the GitHub Sponsors button
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: []
open_collective: ""
ko_fi: ""
custom: ["https://meshflow.dev/sponsor"]
