"""Context window pruning — sliding window and summary compression.

Prevents agents from exceeding LLM context limits on long conversations.
Two strategies:
- SlidingWindowPruner: keep the N most recent messages (O(1), lossless for tail)
- SummaryPruner:       compress old messages into a rolling summary message
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


_CHARS_PER_TOKEN = 4


def _estimate_tokens(messages: list[dict[str, Any]]) -> int:
    total = 0
    for m in messages:
        content = m.get("content", "")
        if isinstance(content, str):
            total += max(1, len(content) // _CHARS_PER_TOKEN)
        elif isinstance(content, list):
            for block in content:
                if isinstance(block, dict):
                    total += max(1, len(str(block.get("text", block.get("content", "")))) // _CHARS_PER_TOKEN)
    return total


@dataclass
class PruneResult:
    """Metadata about what pruning did."""
    messages: list[dict[str, Any]]
    original_count: int
    pruned_count: int
    estimated_tokens: int
    strategy: str

    @property
    def removed_count(self) -> int:
        return self.original_count - self.pruned_count


class SlidingWindowPruner:
    """Keep the most recent ``max_messages`` messages.

    The system message (``role == "system"``) is always preserved at index 0.
    The first human message after the system prompt is also preserved so the
    agent retains task context.

    Parameters
    ----------
    max_messages:
        Maximum number of non-system messages to keep.
    preserve_system:
        If True (default), the system message is always kept regardless of
        ``max_messages``.

    Example
    -------
    ::

        pruner = SlidingWindowPruner(max_messages=10)
        messages = pruner.prune(conversation_messages)
    """

    def __init__(self, max_messages: int = 20, *, preserve_system: bool = True) -> None:
        if max_messages < 1:
            raise ValueError("max_messages must be >= 1")
        self.max_messages = max_messages
        self.preserve_system = preserve_system

    def prune(self, messages: list[dict[str, Any]]) -> PruneResult:
        """Return pruned message list and metadata."""
        original = list(messages)
        if len(original) <= self.max_messages:
            return PruneResult(
                messages=original,
                original_count=len(original),
                pruned_count=len(original),
                estimated_tokens=_estimate_tokens(original),
                strategy="sliding_window",
            )

        system: list[dict[str, Any]] = []
        rest: list[dict[str, Any]] = []
        for m in original:
            if self.preserve_system and m.get("role") == "system":
                system.append(m)
            else:
                rest.append(m)

        keep = rest[-self.max_messages:]
        result = system + keep
        return PruneResult(
            messages=result,
            original_count=len(original),
            pruned_count=len(result),
            estimated_tokens=_estimate_tokens(result),
            strategy="sliding_window",
        )


class SummaryPruner:
    """Compress old messages into a rolling summary when context grows too large.

    When the estimated token count of the conversation exceeds ``max_tokens``,
    all messages older than ``keep_recent`` are summarized into a single
    ``summary`` assistant message.  The summary is generated by calling
    ``summarize_fn`` (async or sync) with the old messages.

    If no ``summarize_fn`` is provided, a simple extractive summary is used
    (first sentence of each assistant turn).

    Parameters
    ----------
    max_tokens:
        Token threshold that triggers compression.
    keep_recent:
        Number of recent messages always kept verbatim after compression.
    summarize_fn:
        Optional async or sync callable that takes
        ``list[dict]`` and returns a summary string.

    Example
    -------
    ::

        pruner = SummaryPruner(max_tokens=4000, keep_recent=6)
        result = await pruner.prune(messages)
        messages = result.messages
    """

    def __init__(
        self,
        max_tokens: int = 4000,
        keep_recent: int = 6,
        summarize_fn: Any = None,
    ) -> None:
        if keep_recent < 2:
            raise ValueError("keep_recent must be >= 2")
        self.max_tokens = max_tokens
        self.keep_recent = keep_recent
        self._summarize_fn = summarize_fn

    async def prune(self, messages: list[dict[str, Any]]) -> PruneResult:
        """Prune and compress messages, returning a PruneResult."""
        original = list(messages)
        estimated = _estimate_tokens(original)

        if estimated <= self.max_tokens:
            return PruneResult(
                messages=original,
                original_count=len(original),
                pruned_count=len(original),
                estimated_tokens=estimated,
                strategy="summary_noop",
            )

        system: list[dict[str, Any]] = []
        rest: list[dict[str, Any]] = []
        for m in original:
            if m.get("role") == "system":
                system.append(m)
            else:
                rest.append(m)

        to_summarize = rest[: max(0, len(rest) - self.keep_recent)]
        to_keep = rest[max(0, len(rest) - self.keep_recent):]

        if not to_summarize:
            return PruneResult(
                messages=original,
                original_count=len(original),
                pruned_count=len(original),
                estimated_tokens=estimated,
                strategy="summary_noop",
            )

        summary_text = await self._build_summary(to_summarize)
        summary_msg: dict[str, Any] = {
            "role": "assistant",
            "content": f"[Conversation summary]\n{summary_text}",
        }

        result = system + [summary_msg] + to_keep
        return PruneResult(
            messages=result,
            original_count=len(original),
            pruned_count=len(result),
            estimated_tokens=_estimate_tokens(result),
            strategy="summary",
        )

    async def _build_summary(self, messages: list[dict[str, Any]]) -> str:
        if self._summarize_fn is not None:
            import inspect
            if inspect.iscoroutinefunction(self._summarize_fn):
                return await self._summarize_fn(messages)
            return self._summarize_fn(messages)
        return self._extractive_summary(messages)

    @staticmethod
    def _extractive_summary(messages: list[dict[str, Any]]) -> str:
        lines: list[str] = []
        for m in messages:
            role = m.get("role", "unknown")
            content = m.get("content", "")
            if isinstance(content, list):
                content = " ".join(
                    str(b.get("text", b.get("content", "")))
                    for b in content
                    if isinstance(b, dict)
                )
            text = str(content).strip()
            first_sentence = (text.split(".")[0] + ".") if "." in text else text[:120]
            if first_sentence:
                lines.append(f"{role}: {first_sentence}")
        return "\n".join(lines)
